# Server Configuration
server.port=8080
server.servlet.context-path=/

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Application Name
spring.application.name=onlykashmir

# DevTools
spring.devtools.restart.enabled=true